import type { EntitySchema } from './types'

export const chargeSchema: EntitySchema = {
  properties: [
    'id',
    'object',
    'paid',
    'order',
    'amount',
    'review',
    'source',
    'status',
    'created',
    'dispute',
    'invoice',
    'outcome',
    'refunds',
    'captured',
    'currency',
    'customer',
    'livemode',
    'metadata',
    'refunded',
    'shipping',
    'application',
    'description',
    'destination',
    'failure_code',
    'on_behalf_of',
    'fraud_details',
    'receipt_email',
    'payment_intent',
    'receipt_number',
    'transfer_group',
    'amount_refunded',
    'application_fee',
    'failure_message',
    'source_transfer',
    'balance_transaction',
    'statement_descriptor',
    'payment_method_details',
  ],
} as const
