#!/usr/bin/env tsx
import * as esbuild from 'esbuild'
import path from 'node:path'
import fs from 'node:fs'
import { fileURLToPath } from 'node:url'
import { nodePrefixBuiltinsPlugin, rawTsBundledPlugin } from '../tsup.config'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.resolve(__dirname, '..')
const srcDir = path.join(rootDir, 'src/supabase/edge-functions')
const outDir = path.join(rootDir, 'dist/supabase/functions')

export function generateEmbeddedMigrations() {
  const migrationsDir = path.join(rootDir, 'src/database/migrations')
  const outFile = path.join(rootDir, 'src/database/migrations-embedded.ts')

  const files = fs
    .readdirSync(migrationsDir)
    .filter((f: string) => f.endsWith('.sql'))
    .sort()

  const migrations = files.map((filename: string) => ({
    name: filename,
    sql: fs.readFileSync(path.join(migrationsDir, filename), 'utf-8'),
  }))

  const lines = [
    '// AUTO-GENERATED by scripts/build-functions.ts — do not edit manually.',
    '// Run `tsx scripts/build-functions.ts` (or the build) to regenerate.',
    '',
    'export type EmbeddedMigration = {',
    '  name: string',
    '  sql: string',
    '}',
    '',
    `export const embeddedMigrations: EmbeddedMigration[] = ${JSON.stringify(migrations, null, 2)}`,
    '',
  ]

  fs.writeFileSync(outFile, lines.join('\n'), 'utf-8')
  console.log(`Generated ${outFile} with ${migrations.length} migrations`)
}

if (!fs.existsSync(srcDir)) {
  console.error(`Source directory not found: ${srcDir}`)
  process.exit(1)
}

if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true })
}

const files = fs.readdirSync(srcDir).filter((f: string) => f.endsWith('.ts'))

console.log(`Found ${files.length} functions in ${srcDir}`)

async function build() {
  generateEmbeddedMigrations()

  for (const file of files) {
    const name = path.basename(file, '.ts')
    const entryPoint = path.join(srcDir, file)
    const functionOutDir = path.join(outDir, name)

    if (!fs.existsSync(functionOutDir)) {
      fs.mkdirSync(functionOutDir, { recursive: true })
    }

    const outfile = path.join(functionOutDir, 'index.js')
    console.log(`Building ${name} -> ${outfile}`)

    try {
      await esbuild.build({
        entryPoints: [entryPoint],
        bundle: true,
        outfile: outfile,
        format: 'esm',
        target: 'esnext',
        platform: 'neutral',
        external: ['npm:*', 'node:*', 'jsr:*', 'chalk', 'inquirer'],
        plugins: [nodePrefixBuiltinsPlugin(), rawTsBundledPlugin],
        logLevel: 'info',
      })
    } catch (error) {
      console.error(`Failed to build ${name}:`, error)
      process.exit(1)
    }
  }
}

build()
