/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline_setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set up destination schema
         * @description Creates destination tables and applies migrations. Safe to call multiple times.
         */
        post: operations["pipeline_setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline_teardown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tear down destination schema
         * @description Drops destination tables. Irreversible.
         */
        post: operations["pipeline_teardown"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline_check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check connector connection
         * @description Validates the source/destination config and tests connectivity.
         */
        get: operations["pipeline_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source_discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover available streams
         * @description Streams NDJSON messages (catalog, logs, traces) for the configured source.
         */
        post: operations["source_discover"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline_read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Read records from source
         * @description Streams NDJSON messages (records, state, catalog). Optional NDJSON body provides live events as input.
         */
        post: operations["pipeline_read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline_write": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Write records to destination
         * @description Reads NDJSON messages from the request body and writes them to the destination. Pipe /read output as input.
         */
        post: operations["pipeline_write"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline_sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run sync pipeline (read → write)
         * @description Without a request body, reads from the source connector and writes to the destination (backfill mode). With an NDJSON request body, uses the provided messages as input instead of reading from the source (push mode — e.g. piped webhook events).
         */
        post: operations["pipeline_sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available source connectors */
        get: operations["meta_sources_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/sources/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get source connector spec */
        get: operations["meta_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available destination connectors */
        get: operations["meta_destinations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/destinations/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get destination connector spec */
        get: operations["meta_destinations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Message: components["schemas"]["RecordMessage"] | components["schemas"]["StateMessage"] | components["schemas"]["CatalogMessage"] | components["schemas"]["LogMessage"] | components["schemas"]["TraceMessage"] | components["schemas"]["SpecMessage"] | components["schemas"]["ConnectionStatusMessage"] | components["schemas"]["ControlMessage"] | components["schemas"]["EofMessage"];
        RecordMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "record";
            /** @description One record for one stream. */
            record: {
                /** @description Stream (table) name this record belongs to. */
                stream: string;
                /** @description The record payload as a key-value map. */
                data: {
                    [key: string]: unknown;
                };
                /**
                 * Format: date-time
                 * @description ISO 8601 timestamp when the record was emitted by the source.
                 */
                emitted_at: string;
            };
        };
        StateMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "state";
            /** @description Per-stream checkpoint for resumable syncs. */
            state: {
                /** @description Stream being checkpointed. */
                stream: string;
                /** @description Opaque checkpoint data — only the source understands its contents. The orchestrator persists it keyed by stream and passes it back on resume. */
                data: unknown;
            };
        };
        CatalogMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "catalog";
            /** @description Catalog of available streams. */
            catalog: {
                /** @description All streams available from this source. */
                streams: {
                    /** @description Collection name (e.g. "customers", "invoices", "pg_public.users"). */
                    name: string;
                    /** @description Paths to fields that uniquely identify a record within this stream. Supports composite keys and nested paths. e.g. [["id"]] or [["account_id"], ["created"]] */
                    primary_key: string[][];
                    /** @description JSON Schema describing the record shape. Discovered at runtime or provided by config. */
                    json_schema?: {
                        [key: string]: unknown;
                    };
                    /** @description Source-specific metadata that applies to every record in this stream. The destination can use these for schema naming, partitioning, etc. Examples: Stripe: { api_version, account_id, live_mode }. */
                    metadata?: {
                        [key: string]: unknown;
                    };
                }[];
            };
        };
        LogMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "log";
            /** @description Structured log output from a connector. */
            log: {
                /**
                 * @description Log severity level.
                 * @enum {string}
                 */
                level: "debug" | "info" | "warn" | "error";
                /** @description Human-readable log message. */
                message: string;
            };
        };
        TraceMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "trace";
            /** @description Diagnostic/status payload with subtypes for error, stream status, and estimates. */
            trace: {
                /** @constant */
                trace_type: "error";
                /** @description Structured error from a connector. */
                error: {
                    /**
                     * @description Error category — lets the orchestrator decide whether to retry, alert, or abort.
                     * @enum {string}
                     */
                    failure_type: "config_error" | "system_error" | "transient_error" | "auth_error";
                    /** @description Human-readable error description. */
                    message: string;
                    /** @description Stream that triggered the error, if applicable. */
                    stream?: string;
                    /** @description Full stack trace for debugging. */
                    stack_trace?: string;
                };
            } | {
                /** @constant */
                trace_type: "stream_status";
                /** @description Per-stream status update. */
                stream_status: {
                    /** @description Stream being reported on. */
                    stream: string;
                    /**
                     * @description Current phase of the stream within this sync run.
                     * @enum {string}
                     */
                    status: "started" | "running" | "complete" | "incomplete";
                };
            } | {
                /** @constant */
                trace_type: "estimate";
                /** @description Sync progress estimate for a stream. */
                estimate: {
                    /** @description Stream being estimated. */
                    stream: string;
                    /** @description Estimated total row count for this stream. */
                    row_count?: number;
                    /** @description Estimated total byte count for this stream. */
                    byte_count?: number;
                };
            };
        };
        SpecMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "spec";
            /** @description JSON Schema describing the configuration a connector requires. */
            spec: {
                /** @description JSON Schema for the connector's configuration object. */
                config: {
                    [key: string]: unknown;
                };
                /** @description JSON Schema for per-stream state (cursor/checkpoint shape). */
                stream_state?: {
                    [key: string]: unknown;
                };
                /** @description JSON Schema for the read() input parameter (e.g. a webhook event). */
                input?: {
                    [key: string]: unknown;
                };
            };
        };
        ConnectionStatusMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "connection_status";
            /** @description Result of a connection check. */
            connection_status: {
                /**
                 * @description Whether the connection check passed.
                 * @enum {string}
                 */
                status: "succeeded" | "failed";
                /** @description Human-readable explanation of the check result. */
                message?: string;
            };
        };
        ControlMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "control";
            /** @description Control signal from a connector to the orchestrator. */
            control: {
                /**
                 * @description What kind of control action the connector is requesting.
                 * @enum {string}
                 */
                control_type: "config_update";
                /** @description Config fields to merge into the active connector configuration. */
                config: {
                    [key: string]: unknown;
                };
            };
        };
        EofMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "eof";
            /** @description Terminal payload — tells the client why the stream ended. */
            eof: {
                /**
                 * @description Why the stream ended.
                 * @enum {string}
                 */
                reason: "complete" | "state_limit" | "time_limit" | "error";
            };
        };
        DestinationOutput: components["schemas"]["StateMessageOutput"] | components["schemas"]["TraceMessageOutput"] | components["schemas"]["LogMessageOutput"] | components["schemas"]["EofMessageOutput"];
        MessageOutput: components["schemas"]["RecordMessageOutput"] | components["schemas"]["StateMessageOutput"] | components["schemas"]["CatalogMessageOutput"] | components["schemas"]["LogMessageOutput"] | components["schemas"]["TraceMessageOutput"] | components["schemas"]["SpecMessageOutput"] | components["schemas"]["ConnectionStatusMessageOutput"] | components["schemas"]["ControlMessageOutput"] | components["schemas"]["EofMessageOutput"];
        RecordMessageOutput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "record";
            /** @description One record for one stream. */
            record: {
                /** @description Stream (table) name this record belongs to. */
                stream: string;
                /** @description The record payload as a key-value map. */
                data: {
                    [key: string]: unknown;
                };
                /**
                 * Format: date-time
                 * @description ISO 8601 timestamp when the record was emitted by the source.
                 */
                emitted_at: string;
            };
        };
        StateMessageOutput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "state";
            /** @description Per-stream checkpoint for resumable syncs. */
            state: {
                /** @description Stream being checkpointed. */
                stream: string;
                /** @description Opaque checkpoint data — only the source understands its contents. The orchestrator persists it keyed by stream and passes it back on resume. */
                data: unknown;
            };
        };
        CatalogMessageOutput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "catalog";
            /** @description Catalog of available streams. */
            catalog: {
                /** @description All streams available from this source. */
                streams: {
                    /** @description Collection name (e.g. "customers", "invoices", "pg_public.users"). */
                    name: string;
                    /** @description Paths to fields that uniquely identify a record within this stream. Supports composite keys and nested paths. e.g. [["id"]] or [["account_id"], ["created"]] */
                    primary_key: string[][];
                    /** @description JSON Schema describing the record shape. Discovered at runtime or provided by config. */
                    json_schema?: {
                        [key: string]: unknown;
                    };
                    /** @description Source-specific metadata that applies to every record in this stream. The destination can use these for schema naming, partitioning, etc. Examples: Stripe: { api_version, account_id, live_mode }. */
                    metadata?: {
                        [key: string]: unknown;
                    };
                }[];
            };
        };
        LogMessageOutput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "log";
            /** @description Structured log output from a connector. */
            log: {
                /**
                 * @description Log severity level.
                 * @enum {string}
                 */
                level: "debug" | "info" | "warn" | "error";
                /** @description Human-readable log message. */
                message: string;
            };
        };
        TraceMessageOutput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "trace";
            /** @description Diagnostic/status payload with subtypes for error, stream status, and estimates. */
            trace: {
                /** @constant */
                trace_type: "error";
                /** @description Structured error from a connector. */
                error: {
                    /**
                     * @description Error category — lets the orchestrator decide whether to retry, alert, or abort.
                     * @enum {string}
                     */
                    failure_type: "config_error" | "system_error" | "transient_error" | "auth_error";
                    /** @description Human-readable error description. */
                    message: string;
                    /** @description Stream that triggered the error, if applicable. */
                    stream?: string;
                    /** @description Full stack trace for debugging. */
                    stack_trace?: string;
                };
            } | {
                /** @constant */
                trace_type: "stream_status";
                /** @description Per-stream status update. */
                stream_status: {
                    /** @description Stream being reported on. */
                    stream: string;
                    /**
                     * @description Current phase of the stream within this sync run.
                     * @enum {string}
                     */
                    status: "started" | "running" | "complete" | "incomplete";
                };
            } | {
                /** @constant */
                trace_type: "estimate";
                /** @description Sync progress estimate for a stream. */
                estimate: {
                    /** @description Stream being estimated. */
                    stream: string;
                    /** @description Estimated total row count for this stream. */
                    row_count?: number;
                    /** @description Estimated total byte count for this stream. */
                    byte_count?: number;
                };
            };
        };
        SpecMessageOutput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "spec";
            /** @description JSON Schema describing the configuration a connector requires. */
            spec: {
                /** @description JSON Schema for the connector's configuration object. */
                config: {
                    [key: string]: unknown;
                };
                /** @description JSON Schema for per-stream state (cursor/checkpoint shape). */
                stream_state?: {
                    [key: string]: unknown;
                };
                /** @description JSON Schema for the read() input parameter (e.g. a webhook event). */
                input?: {
                    [key: string]: unknown;
                };
            };
        };
        ConnectionStatusMessageOutput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "connection_status";
            /** @description Result of a connection check. */
            connection_status: {
                /**
                 * @description Whether the connection check passed.
                 * @enum {string}
                 */
                status: "succeeded" | "failed";
                /** @description Human-readable explanation of the check result. */
                message?: string;
            };
        };
        ControlMessageOutput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "control";
            /** @description Control signal from a connector to the orchestrator. */
            control: {
                /**
                 * @description What kind of control action the connector is requesting.
                 * @enum {string}
                 */
                control_type: "config_update";
                /** @description Config fields to merge into the active connector configuration. */
                config: {
                    [key: string]: unknown;
                };
            };
        };
        EofMessageOutput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "eof";
            /** @description Terminal payload — tells the client why the stream ended. */
            eof: {
                /**
                 * @description Why the stream ended.
                 * @enum {string}
                 */
                reason: "complete" | "state_limit" | "time_limit" | "error";
            };
        };
        StripeSourceConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "StripeSourceConfig";
            /** @description Stripe API key (sk_test_... or sk_live_...) */
            api_key: string;
            /** @description Stripe account ID (resolved from API if omitted) */
            account_id?: string;
            /** @description Whether this is a live mode sync */
            livemode?: boolean;
            /** @description Stripe API version (e.g. 2025-04-30.basil) */
            api_version?: string;
            /**
             * Format: uri
             * @description Override the Stripe API base URL (e.g. http://localhost:12111 for stripe-mock)
             */
            base_url?: string;
            /**
             * Format: uri
             * @description URL for managed webhook endpoint registration
             */
            webhook_url?: string;
            /** @description Webhook signing secret (whsec_...) for signature verification */
            webhook_secret?: string;
            /** @description Enable WebSocket streaming for live events */
            websocket?: boolean;
            /** @description Enable events API polling for incremental sync after backfill */
            poll_events?: boolean;
            /** @description Port for built-in webhook HTTP listener (e.g. 4242) */
            webhook_port?: number;
            /** @description Object types to re-fetch from Stripe API on webhook (e.g. ["subscription"]) */
            revalidate_objects?: string[];
            /** @description Max objects to backfill per stream (useful for testing) */
            backfill_limit?: number;
            /** @description Max Stripe API requests per second (default: 25) */
            rate_limit?: number;
            /** @description Number of time-range segments for parallel backfill (default: 200) */
            backfill_concurrency?: number;
        };
        PostgresDestinationConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "PostgresDestinationConfig";
            /** @description Postgres connection string (alias for connection_string) */
            url?: string;
            /** @description Postgres connection string */
            connection_string?: string;
            /** @description Postgres host (required for AWS IAM) */
            host?: string;
            /**
             * @description Postgres port
             * @default 5432
             */
            port: number;
            /** @description Database name (required for AWS IAM) */
            database?: string;
            /** @description Database user (required for AWS IAM) */
            user?: string;
            /** @description Target schema name (e.g. "stripe_sync") */
            schema: string;
            /**
             * @description Records to buffer before flushing
             * @default 100
             */
            batch_size: number;
            /** @description AWS RDS IAM authentication config */
            aws?: {
                /** @description AWS region for RDS instance */
                region: string;
                /** @description IAM role ARN to assume (cross-account) */
                role_arn?: string;
                /** @description External ID for STS AssumeRole */
                external_id?: string;
            };
            /** @description PEM-encoded CA certificate for SSL verification (required for verify-ca / verify-full with a private CA) */
            ssl_ca_pem?: string;
        };
        GoogleSheetsDestinationConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "GoogleSheetsDestinationConfig";
            /** @description Google OAuth2 client ID (env: GOOGLE_CLIENT_ID) */
            client_id?: string;
            /** @description Google OAuth2 client secret (env: GOOGLE_CLIENT_SECRET) */
            client_secret?: string;
            /** @description OAuth2 access token */
            access_token: string;
            /** @description OAuth2 refresh token */
            refresh_token: string;
            /** @description Target spreadsheet ID (created if omitted) */
            spreadsheet_id?: string;
            /**
             * @description Title when creating a new spreadsheet
             * @default Stripe Sync
             */
            spreadsheet_title: string;
            /**
             * @description Rows per Sheets API append call
             * @default 50
             */
            batch_size: number;
        };
        SourceConfig: components["schemas"]["StripeSourceConfig"];
        DestinationConfig: components["schemas"]["PostgresDestinationConfig"] | components["schemas"]["GoogleSheetsDestinationConfig"];
        PipelineConfig: {
            source: components["schemas"]["SourceConfig"];
            destination: components["schemas"]["DestinationConfig"];
            streams?: {
                name: string;
                /** @enum {string} */
                sync_mode?: "incremental" | "full_refresh";
                fields?: string[];
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                    };
                };
            };
        };
    };
    pipeline_setup: {
        parameters: {
            query?: never;
            header?: {
                /** @description JSON-encoded PipelineConfig: { source: { type, ...config }, destination: { type, ...config }, streams } */
                "x-pipeline"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setup complete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Invalid params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
        };
    };
    pipeline_teardown: {
        parameters: {
            query?: never;
            header?: {
                /** @description JSON-encoded PipelineConfig: { source: { type, ...config }, destination: { type, ...config }, streams } */
                "x-pipeline"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Teardown complete */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
        };
    };
    pipeline_check: {
        parameters: {
            query?: never;
            header?: {
                /** @description JSON-encoded PipelineConfig: { source: { type, ...config }, destination: { type, ...config }, streams } */
                "x-pipeline"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection check result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        source: {
                            /** @enum {string} */
                            status: "succeeded" | "failed";
                            message?: string;
                        };
                        destination: {
                            /** @enum {string} */
                            status: "succeeded" | "failed";
                            message?: string;
                        };
                    };
                };
            };
            /** @description Invalid params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
        };
    };
    source_discover: {
        parameters: {
            query?: never;
            header?: {
                /** @description JSON-encoded PipelineConfig: { source: { type, ...config }, destination: { type, ...config }, streams } */
                "x-pipeline"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NDJSON stream of discover messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["MessageOutput"];
                };
            };
            /** @description Invalid params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
        };
    };
    pipeline_read: {
        parameters: {
            query?: {
                /** @description Stop streaming after N state messages. */
                state_limit?: number;
                /** @description Stop streaming after N seconds. */
                time_limit?: number;
            };
            header?: {
                /** @description JSON-encoded PipelineConfig: { source: { type, ...config }, destination: { type, ...config }, streams } */
                "x-pipeline"?: string;
                /** @description JSON-encoded per-stream cursor state. Engine uses this if present, falls back to StateStore. */
                "x-state"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NDJSON stream of sync messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["MessageOutput"];
                };
            };
            /** @description Invalid params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
        };
    };
    pipeline_write: {
        parameters: {
            query?: never;
            header?: {
                /** @description JSON-encoded PipelineConfig: { source: { type, ...config }, destination: { type, ...config }, streams } */
                "x-pipeline"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-ndjson": components["schemas"]["Message"];
            };
        };
        responses: {
            /** @description NDJSON stream of write result messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["DestinationOutput"];
                };
            };
            /** @description Invalid params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
        };
    };
    pipeline_sync: {
        parameters: {
            query?: {
                /** @description Stop streaming after N state messages. */
                state_limit?: number;
                /** @description Stop streaming after N seconds. */
                time_limit?: number;
            };
            header?: {
                /** @description JSON-encoded PipelineConfig: { source: { type, ...config }, destination: { type, ...config }, streams } */
                "x-pipeline"?: string;
                /** @description JSON-encoded per-stream cursor state. Engine uses this if present, falls back to StateStore. */
                "x-state"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NDJSON stream of sync messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["DestinationOutput"];
                };
            };
            /** @description Invalid params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
        };
    };
    meta_sources_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available source connectors with their JSON Schema configs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            config_schema: {
                                [key: string]: unknown;
                            };
                            type: string;
                        }[];
                    };
                };
            };
        };
    };
    meta_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source connector spec */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        config_schema: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            /** @description Source connector not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    meta_destinations_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available destination connectors with their JSON Schema configs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            config_schema: {
                                [key: string]: unknown;
                            };
                            type: string;
                        }[];
                    };
                };
            };
        };
    };
    meta_destinations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Destination connector spec */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        config_schema: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            /** @description Destination connector not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
