/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline_check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check connector connection
         * @description Validates the source/destination config and tests connectivity. Streams NDJSON messages (connection_status, log, trace) tagged with _emitted_by.
         */
        post: operations["pipeline_check"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline_setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set up destination schema
         * @description Creates destination tables and applies migrations. Streams NDJSON messages (control, log, trace) tagged with _emitted_by. Pass ?only=destination to run destination setup alone (e.g. optimistic table creation) or ?only=source to isolate the source.
         */
        post: operations["pipeline_setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline_teardown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tear down destination schema
         * @description Drops destination tables. Streams NDJSON messages (log, trace) tagged with _emitted_by. Pass ?only=destination or ?only=source to run a single side.
         */
        post: operations["pipeline_teardown"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source_discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover available streams
         * @description Streams NDJSON messages (catalog, logs, traces) for the configured source.
         */
        post: operations["source_discover"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline_read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Read records from source
         * @description Streams NDJSON messages (records, state, catalog). Optional NDJSON body provides live events as input.
         */
        post: operations["pipeline_read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline_write": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Write records to destination
         * @description Reads NDJSON messages from the request body and writes them to the destination. Pipe /read output as input.
         */
        post: operations["pipeline_write"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline_sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run sync pipeline (read → write)
         * @description Without a request body, reads from the source connector and writes to the destination (backfill mode). With an NDJSON request body, uses the provided messages as input instead of reading from the source (push mode — e.g. piped webhook events).
         */
        post: operations["pipeline_sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available source connectors */
        get: operations["meta_sources_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/sources/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get source connector spec */
        get: operations["meta_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available destination connectors */
        get: operations["meta_destinations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/destinations/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get destination connector spec */
        get: operations["meta_destinations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a SQL query against a Postgres connection */
        post: operations["internalQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RecordMessage: {
            /** @description Who emitted this message: "source/{type}", "destination/{type}", or "engine". Set by the engine. */
            _emitted_by?: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp when the engine observed this message.
             */
            _ts?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "record";
            /** @description One record for one stream. */
            record: {
                /** @description Stream (table) name this record belongs to. */
                stream: string;
                /** @description The record payload as a key-value map. */
                data: {
                    [key: string]: unknown;
                };
                /**
                 * Format: date-time
                 * @description ISO 8601 timestamp when the record was emitted by the source.
                 */
                emitted_at: string;
            };
        };
        SourceStateMessage: {
            /** @description Who emitted this message: "source/{type}", "destination/{type}", or "engine". Set by the engine. */
            _emitted_by?: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp when the engine observed this message.
             */
            _ts?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "source_state";
            source_state: {
                /**
                 * @default stream
                 * @constant
                 */
                state_type: "stream";
                /** @description Stream being checkpointed. */
                stream: string;
                /** @description Opaque checkpoint data — only the source understands its contents. The orchestrator persists it keyed by stream and passes it back on resume. */
                data: unknown;
            } | {
                /** @constant */
                state_type: "global";
                /** @description Sync-wide state shared across all streams (e.g. a global events cursor). */
                data: unknown;
            };
        };
        CatalogMessage: {
            /** @description Who emitted this message: "source/{type}", "destination/{type}", or "engine". Set by the engine. */
            _emitted_by?: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp when the engine observed this message.
             */
            _ts?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "catalog";
            /** @description Catalog of available streams. */
            catalog: {
                /** @description All streams available from this source. */
                streams: {
                    /** @description Collection name (e.g. "customers", "invoices", "pg_public.users"). */
                    name: string;
                    /** @description Paths to fields that uniquely identify a record within this stream. Supports composite keys and nested paths. e.g. [["id"]] or [["account_id"], ["created"]] */
                    primary_key: string[][];
                    /** @description JSON Schema describing the record shape. Discovered at runtime or provided by config. */
                    json_schema?: {
                        [key: string]: unknown;
                    };
                    /** @description Source-specific metadata that applies to every record in this stream. The destination can use these for schema naming, partitioning, etc. Examples: Stripe: { api_version, account_id, live_mode }. */
                    metadata?: {
                        [key: string]: unknown;
                    };
                    /** @description Field whose value increases monotonically. Destination uses it to skip stale writes (e.g. "updated"). */
                    newer_than_field?: string;
                    /** @description Field in record data that signals a soft delete (e.g. "deleted"). Destination uses this to classify upserts as deletes when the field is truthy. */
                    soft_delete_field?: string;
                }[];
            };
        };
        LogMessage: {
            /** @description Who emitted this message: "source/{type}", "destination/{type}", or "engine". Set by the engine. */
            _emitted_by?: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp when the engine observed this message.
             */
            _ts?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "log";
            /** @description Structured log output from a connector. */
            log: {
                /**
                 * @description Log severity level.
                 * @enum {string}
                 */
                level: "debug" | "info" | "warn" | "error";
                /** @description Human-readable log message. */
                message: string;
                /** @description Structured log fields emitted alongside the message. */
                data?: {
                    [key: string]: unknown;
                };
            };
        };
        SpecMessage: {
            /** @description Who emitted this message: "source/{type}", "destination/{type}", or "engine". Set by the engine. */
            _emitted_by?: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp when the engine observed this message.
             */
            _ts?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "spec";
            /** @description JSON Schema describing the configuration a connector requires. */
            spec: {
                /** @description JSON Schema for the connector's configuration object. */
                config: {
                    [key: string]: unknown;
                };
                /** @description JSON Schema for per-stream state (cursor/checkpoint shape). See also SourceState.global for sync-wide cursors. */
                source_state_stream?: {
                    [key: string]: unknown;
                };
                /** @description JSON Schema for the read() input parameter (e.g. a webhook event). */
                source_input?: {
                    [key: string]: unknown;
                };
            };
        };
        ConnectionStatusMessage: {
            /** @description Who emitted this message: "source/{type}", "destination/{type}", or "engine". Set by the engine. */
            _emitted_by?: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp when the engine observed this message.
             */
            _ts?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "connection_status";
            /** @description Result of a connection check. */
            connection_status: {
                /**
                 * @description Whether the connection check passed.
                 * @enum {string}
                 */
                status: "succeeded" | "failed";
                /** @description Human-readable explanation of the check result. */
                message?: string;
            };
        };
        StreamStatusMessage: {
            /** @description Who emitted this message: "source/{type}", "destination/{type}", or "engine". Set by the engine. */
            _emitted_by?: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp when the engine observed this message.
             */
            _ts?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stream_status";
            /** @description Stream lifecycle event. Sources emit these; the engine tracks stream progress from them. */
            stream_status: {
                /** @description Stream being reported on. */
                stream: string;
                /** @constant */
                status: "start";
                /** @description Full backfill time span for this stream. */
                time_range?: {
                    /** @description Inclusive lower bound (ISO 8601). */
                    gte?: string;
                    /** @description Exclusive upper bound (ISO 8601). */
                    lt?: string;
                };
            } | {
                /** @description Stream being reported on. */
                stream: string;
                /** @constant */
                status: "range_complete";
                /** @description The sub-range that finished. */
                range_complete: {
                    /** @description Inclusive lower bound (ISO 8601). */
                    gte: string;
                    /** @description Exclusive upper bound (ISO 8601). */
                    lt: string;
                };
            } | {
                /** @description Stream being reported on. */
                stream: string;
                /** @constant */
                status: "complete";
            } | {
                /** @description Stream being reported on. */
                stream: string;
                /** @constant */
                status: "error";
                /** @description Human-readable error description. */
                error: string;
            } | {
                /** @description Stream being reported on. */
                stream: string;
                /** @constant */
                status: "skip";
                /** @description Why the stream was skipped. */
                reason: string;
            };
        };
        ControlMessage: {
            /** @description Who emitted this message: "source/{type}", "destination/{type}", or "engine". Set by the engine. */
            _emitted_by?: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp when the engine observed this message.
             */
            _ts?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "control";
            /** @description Control signal from a connector to the orchestrator. */
            control: {
                /** @constant */
                control_type: "source_config";
                source_config: components["schemas"]["SourceStripeConfig"];
            } | {
                /** @constant */
                control_type: "destination_config";
                destination_config: components["schemas"]["DestinationPostgresConfig"] | components["schemas"]["DestinationGoogleSheetsConfig"];
            };
        };
        ProgressMessage: {
            /** @description Who emitted this message: "source/{type}", "destination/{type}", or "engine". Set by the engine. */
            _emitted_by?: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp when the engine observed this message.
             */
            _ts?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "progress";
            progress: components["schemas"]["ProgressPayload"];
        };
        /** @description Periodic sync progress emitted by the engine as a top-level message. Each emission is a full replacement. */
        ProgressPayload: {
            /** @description When this sync started (ISO 8601); generally equals time_ceiling. */
            started_at: string;
            /** @description Wall-clock milliseconds since the sync run started. */
            elapsed_ms: number;
            /** @description Total source_state messages observed so far. */
            global_state_count: number;
            /** @description Set when source or destination emits connection_status: failed. */
            connection_status?: {
                /**
                 * @description Whether the connection check passed.
                 * @enum {string}
                 */
                status: "succeeded" | "failed";
                /** @description Human-readable explanation of the check result. */
                message?: string;
            };
            /** @description Computed aggregates. */
            derived: {
                status: components["schemas"]["RunStatus"];
                /** @description Overall throughput for the entire run. */
                records_per_second: number;
                /** @description State checkpoints per second. */
                states_per_second: number;
            };
            /** @description Per-stream progress, keyed by stream name. */
            streams: {
                [key: string]: components["schemas"]["StreamProgress"];
            };
        };
        /**
         * @description succeeded = all streams completed/skipped; failed = connection_status failed OR any stream errored.
         * @enum {string}
         */
        RunStatus: "started" | "succeeded" | "failed";
        /** @description Per-stream progress snapshot. */
        StreamProgress: {
            /**
             * @description Current state, derived from stream_status events.
             * @enum {string}
             */
            status: "not_started" | "started" | "completed" | "skipped" | "errored";
            /** @description Number of state checkpoints for this stream. */
            state_count: number;
            /** @description Records synced for this stream in this run. */
            record_count: number;
            /** @description Human-readable status message (error reason, skip reason, etc). */
            message?: string;
            /** @description Full backfill time span for this stream. */
            total_range?: {
                /** @description Inclusive lower bound (ISO 8601). */
                gte: string;
                /** @description Exclusive upper bound (ISO 8601). */
                lt: string;
            };
            /** @description Completed time sub-ranges within the total_range. */
            completed_ranges?: {
                /** @description Inclusive lower bound (ISO 8601). */
                gte: string;
                /** @description Exclusive upper bound (ISO 8601). */
                lt: string;
            }[];
        };
        EofMessage: {
            /** @description Who emitted this message: "source/{type}", "destination/{type}", or "engine". Set by the engine. */
            _emitted_by?: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp when the engine observed this message.
             */
            _ts?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "eof";
            eof: components["schemas"]["EofPayload"];
        };
        /** @description Terminal message signaling end of this request. */
        EofPayload: {
            /** @description Terminal run status derived from stream outcomes. */
            status: components["schemas"]["RunStatus"];
            /** @description Whether the client should continue with another request. true when cut off by limits; false when the source iterator exhausted naturally. */
            has_more: boolean;
            /** @description Full sync state at the end of this request. Round-trip this as starting_state on the next request. */
            ending_state?: components["schemas"]["SyncState"];
            /** @description Accumulated progress across all requests in this sync run. */
            run_progress: components["schemas"]["ProgressPayload"];
            /** @description Progress for this specific request only. */
            request_progress: components["schemas"]["ProgressPayload"];
        };
        /** @description Full sync checkpoint with separate sections for source, destination, and sync run. Connectors only see their own section; the engine manages routing. */
        SyncState: {
            source: components["schemas"]["SourceState"];
            /** @description Destination connector state. */
            destination: {
                [key: string]: unknown;
            };
            /** @description Engine-managed run state — run_id, time_ceiling, accumulated progress. */
            sync_run: {
                /** @description Identifies a finite backfill run. Omit for continuous sync. */
                run_id?: string;
                /** @description Frozen upper bound (ISO 8601). Set on first invocation when run_id is present; reused on continuation. */
                time_ceiling?: string;
                /** @description Accumulated progress from prior requests in this run. */
                progress: components["schemas"]["ProgressPayload"];
            };
        };
        /** @description Source connector state — cursors, backfill progress, events cursors. */
        SourceState: {
            /** @description Per-stream checkpoint data, keyed by stream name. */
            streams: {
                [key: string]: unknown;
            };
            /** @description Source-wide state shared across all streams. */
            global: {
                [key: string]: unknown;
            };
        };
        SourceInputMessage: {
            /** @description Who emitted this message: "source/{type}", "destination/{type}", or "engine". Set by the engine. */
            _emitted_by?: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp when the engine observed this message.
             */
            _ts?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "source_input";
            source_input: unknown;
        };
        SourceStripeInput: {
            /** @description Unique identifier for the object. */
            id: string;
            /** @constant */
            object: "event";
            /** @description The connected account that originates the event. */
            account?: string;
            api_version: string | null;
            /** @description Time at which the object was created. Measured in seconds since the Unix epoch. */
            created: number;
            data: {
                object: {
                    [key: string]: unknown;
                };
                previous_attributes?: {
                    [key: string]: unknown;
                };
            };
            /** @description Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode. */
            livemode: boolean;
            /** @description Number of webhooks that haven't been successfully delivered (for example, to return a 20x response) to the URLs you specify. */
            pending_webhooks: number;
            request: {
                id: string | null;
                idempotency_key: string | null;
            } | null;
            /** @description Description of the event (for example, `invoice.created` or `charge.refunded`). */
            type: string;
        };
        SourceConfig: {
            /** @constant */
            type: "stripe";
            stripe: components["schemas"]["SourceStripeConfig"];
        };
        SourceStripeConfig: {
            /** @description Stripe API key (sk_test_... or sk_live_...) */
            api_key: string;
            /** @description Stripe account ID (resolved from API if omitted) */
            account_id?: string;
            /** @description Stripe account creation timestamp in unix seconds (resolved from API if omitted) */
            account_created?: number;
            /** @description Whether this is a live mode sync */
            livemode?: boolean;
            /** @enum {string} */
            api_version?: "2026-03-25.dahlia" | "2026-02-25.clover" | "2026-01-28.clover" | "2025-12-15.clover" | "2025-11-17.clover" | "2025-10-29.clover" | "2025-09-30.clover" | "2025-08-27.basil" | "2025-07-30.basil" | "2025-06-30.basil" | "2025-05-28.basil" | "2025-04-30.basil" | "2025-03-31.basil" | "2025-02-24.acacia" | "2025-01-27.acacia" | "2024-12-18.acacia" | "2024-11-20.acacia" | "2024-10-28.acacia" | "2024-09-30.acacia" | "2024-06-20" | "2024-04-10" | "2024-04-03" | "2023-10-16" | "2023-08-16" | "2022-11-15" | "2022-08-01" | "2020-08-27" | "2020-03-02" | "2019-12-03" | "2019-11-05" | "2019-10-17" | "2019-10-08" | "2019-09-09" | "2019-08-14" | "2019-05-16" | "2019-03-14" | "2019-02-19" | "2019-02-11" | "2018-11-08" | "2018-10-31" | "2018-09-24" | "2018-09-06" | "2018-08-23" | "2018-07-27" | "2018-05-21" | "2018-02-28" | "2018-02-06" | "2018-02-05" | "2018-01-23" | "2017-12-14" | "2017-08-15";
            /**
             * Format: uri
             * @description Override the Stripe API base URL (e.g. http://localhost:12111 for stripe-mock)
             */
            base_url?: string;
            /**
             * Format: uri
             * @description URL for managed webhook endpoint registration
             */
            webhook_url?: string;
            /** @description Webhook signing secret (whsec_...) for signature verification */
            webhook_secret?: string;
            /** @description Enable WebSocket streaming for live events */
            websocket?: boolean;
            /** @description Enable events API polling for incremental sync after backfill */
            poll_events?: boolean;
            /** @description Port for built-in webhook HTTP listener (e.g. 4242) */
            webhook_port?: number;
            /** @description Object types to re-fetch from Stripe API on webhook (e.g. ["subscription"]) */
            revalidate_objects?: string[];
            /** @description Max objects to backfill per stream (useful for testing) */
            backfill_limit?: number;
            /** @description Override max requests per second (default: auto-derived from API key mode — 20 live, 10 test). */
            rate_limit?: number;
        };
        DestinationConfig: {
            /** @constant */
            type: "postgres";
            postgres: components["schemas"]["DestinationPostgresConfig"];
        } | {
            /** @constant */
            type: "google_sheets";
            google_sheets: components["schemas"]["DestinationGoogleSheetsConfig"];
        };
        DestinationPostgresConfig: {
            /** @description Postgres connection string */
            url?: string;
            /** @description Deprecated alias for url; prefer url */
            connection_string?: string;
            /**
             * @description Target schema name (e.g. "stripe")
             * @default public
             */
            schema: string;
            /**
             * @description Records to buffer before flushing
             * @default 100
             */
            batch_size: number;
            /** @description AWS RDS IAM authentication config */
            aws?: {
                /** @description Postgres host for RDS IAM auth */
                host: string;
                /**
                 * @description Postgres port for RDS IAM auth
                 * @default 5432
                 */
                port: number;
                /** @description Database name for RDS IAM auth */
                database: string;
                /** @description Database user for RDS IAM auth */
                user: string;
                /** @description AWS region for RDS instance */
                region: string;
                /** @description IAM role ARN to assume (cross-account) */
                role_arn?: string;
                /** @description External ID for STS AssumeRole */
                external_id?: string;
            };
            /** @description PEM-encoded CA certificate for SSL verification (required for verify-ca / verify-full with a private CA) */
            ssl_ca_pem?: string;
        };
        DestinationGoogleSheetsConfig: {
            /** @description Google OAuth2 client ID (env: GOOGLE_CLIENT_ID) */
            client_id?: string;
            /** @description Google OAuth2 client secret (env: GOOGLE_CLIENT_SECRET) */
            client_secret?: string;
            /** @description OAuth2 access token */
            access_token: string;
            /** @description OAuth2 refresh token */
            refresh_token: string;
            /** @description Target spreadsheet ID (created if omitted) */
            spreadsheet_id?: string;
            /**
             * @description Title when creating a new spreadsheet
             * @default Stripe Sync
             */
            spreadsheet_title: string;
            /**
             * @description Rows per Sheets API append call
             * @default 50
             */
            batch_size: number;
        };
        Message: components["schemas"]["RecordMessage"] | components["schemas"]["SourceStateMessage"] | components["schemas"]["CatalogMessage"] | components["schemas"]["LogMessage"] | components["schemas"]["SpecMessage"] | components["schemas"]["ConnectionStatusMessage"] | components["schemas"]["StreamStatusMessage"] | components["schemas"]["ControlMessage"] | components["schemas"]["ProgressMessage"] | components["schemas"]["EofMessage"] | components["schemas"]["SourceInputMessage"];
        DiscoverOutput: components["schemas"]["CatalogMessage"] | components["schemas"]["LogMessage"];
        DestinationOutput: components["schemas"]["Message"];
        SyncOutput: components["schemas"]["SourceStateMessage"] | components["schemas"]["StreamStatusMessage"] | components["schemas"]["ProgressMessage"] | components["schemas"]["ConnectionStatusMessage"] | components["schemas"]["LogMessage"] | components["schemas"]["EofMessage"] | components["schemas"]["ControlMessage"];
        CheckOutput: components["schemas"]["ConnectionStatusMessage"] | components["schemas"]["LogMessage"];
        SetupOutput: components["schemas"]["ControlMessage"] | components["schemas"]["LogMessage"];
        TeardownOutput: components["schemas"]["LogMessage"];
        TypedSourceInputMessage: {
            /** @constant */
            type: "source_input";
            source_input: components["schemas"]["SourceStripeInput"];
        };
        PipelineConfig: {
            source: components["schemas"]["SourceConfig"];
            destination: components["schemas"]["DestinationConfig"];
            streams?: {
                /** @description Stream (table) name to sync. */
                name: string;
                /**
                 * @description How the source reads this stream. Defaults to full_refresh.
                 * @enum {string}
                 */
                sync_mode?: "incremental" | "full_refresh";
                /** @description If set, only these fields are synced. */
                fields?: string[];
                /** @description Cap backfill to this many records, then mark the stream complete. */
                backfill_limit?: number;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        hostname: string;
                        commit?: string;
                        commit_url?: string;
                        build_date?: string;
                    };
                };
            };
        };
    };
    pipeline_check: {
        parameters: {
            query?: never;
            header: {
                /** @description JSON-encoded PipelineConfig */
                "x-pipeline": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NDJSON stream of check messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["CheckOutput"];
                };
            };
            /** @description Invalid params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
        };
    };
    pipeline_setup: {
        parameters: {
            query?: {
                /** @description Run only the source or destination side. Useful for optimistic destination setup (e.g. creating tables early in a UI) or isolating a connector when debugging. */
                only?: "source" | "destination";
            };
            header: {
                /** @description JSON-encoded PipelineConfig */
                "x-pipeline": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NDJSON stream of setup messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["SetupOutput"];
                };
            };
            /** @description Invalid params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
        };
    };
    pipeline_teardown: {
        parameters: {
            query?: {
                /** @description Run only the source or destination side. Useful for optimistic destination setup (e.g. creating tables early in a UI) or isolating a connector when debugging. */
                only?: "source" | "destination";
            };
            header: {
                /** @description JSON-encoded PipelineConfig */
                "x-pipeline": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NDJSON stream of teardown messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["TeardownOutput"];
                };
            };
            /** @description Invalid params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
        };
    };
    source_discover: {
        parameters: {
            query?: never;
            header: {
                /** @description JSON-encoded source config ({ type, ...config }) */
                "x-source": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NDJSON stream of discover messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["DiscoverOutput"];
                };
            };
            /** @description Invalid params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
        };
    };
    pipeline_read: {
        parameters: {
            query?: {
                /** @description Stop streaming after N seconds. */
                time_limit?: number;
                /** @description Optional sync run identifier used to track bounded sync progress. */
                run_id?: string;
            };
            header: {
                /** @description JSON-encoded PipelineConfig */
                "x-pipeline": string;
                /** @description JSON-encoded SyncState ({ source, destination, sync_run }). Falls back to empty state if invalid. */
                "x-state"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-ndjson": components["schemas"]["SourceInputMessage"];
            };
        };
        responses: {
            /** @description NDJSON stream of sync messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["Message"];
                };
            };
            /** @description Invalid params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
        };
    };
    pipeline_write: {
        parameters: {
            query?: never;
            header: {
                /** @description JSON-encoded PipelineConfig */
                "x-pipeline": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-ndjson": components["schemas"]["Message"];
            };
        };
        responses: {
            /** @description NDJSON stream of write result messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["DestinationOutput"];
                };
            };
            /** @description Invalid params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
        };
    };
    pipeline_sync: {
        parameters: {
            query?: {
                /** @description Stop streaming after N seconds. */
                time_limit?: number;
                /** @description Optional sync run identifier used to track bounded sync progress. */
                run_id?: string;
            };
            header: {
                /** @description JSON-encoded PipelineConfig */
                "x-pipeline": string;
                /** @description JSON-encoded SyncState ({ source, destination, sync_run }). Falls back to empty state if invalid. */
                "x-state"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-ndjson": components["schemas"]["SourceInputMessage"];
            };
        };
        responses: {
            /** @description NDJSON stream of sync messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["SyncOutput"];
                };
            };
            /** @description Invalid params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
        };
    };
    meta_sources_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available source connectors with their JSON Schema configs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            config_schema: {
                                [key: string]: unknown;
                            };
                            type: string;
                        }[];
                    };
                };
            };
        };
    };
    meta_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source connector spec */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        config_schema: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            /** @description Source connector not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    meta_destinations_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available destination connectors with their JSON Schema configs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            config_schema: {
                                [key: string]: unknown;
                            };
                            type: string;
                        }[];
                    };
                };
            };
        };
    };
    meta_destinations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Destination connector spec */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        config_schema: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            /** @description Destination connector not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    internalQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    connection_string?: string;
                    url?: string;
                    sql: string;
                };
            };
        };
        responses: {
            /** @description Query results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        rows: {
                            [key: string]: unknown;
                        }[];
                        rowCount: number | null;
                    };
                };
            };
            /** @description Invalid params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
        };
    };
}
