import { vitest } from 'vitest'

export const mockStripe = {
  accounts: {
    retrieve: vitest.fn(() =>
      Promise.resolve({
        id: 'acct_test_account',
        object: 'account',
      })
    ),
  },
  checkout: {
    sessions: {
      retrieve: vitest.fn((id) =>
        Promise.resolve({
          id: id,
          object: 'checkout.session',
          customer: 'cus_J7Mkgr8mvbl1eK',
          payment_intent: 'pi_xyz',
          invoice: 'in_xyz',
          subscription: null,
        })
      ),
      listLineItems: vitest.fn(() => ({
        async *[Symbol.asyncIterator]() {
          yield {
            id: 'li_123',
            object: 'item',
            description: 'T-shirt',
            currency: 'usd',
            amount_discount: 0,
            amount_subtotal: 2198,
            amount_tax: 0,
            amount_total: 2198,
            price: {
              id: 'price_1IDQm5JDPojXS6LNM31hxKzp',
              object: 'price',
              active: true,
              billing_scheme: 'per_unit',
              created: 1683237782,
              currency: 'usd',
              custom_unit_amount: null,
              livemode: false,
              lookup_key: null,
              metadata: {},
              nickname: null,
              product: 'prod_NppuJWzzNnD5Ut',
              recurring: null,
              tax_behavior: 'unspecified',
              tiers_mode: null,
              transform_quantity: null,
              type: 'one_time',
              unit_amount: 1099,
              unit_amount_decimal: '1099',
            },
            quantity: 1,
          }
          yield {
            id: 'li_456',
            object: 'item',
            description: 'Hoodie',
            currency: 'usd',
            amount_discount: 0,
            amount_subtotal: 2198,
            amount_tax: 0,
            amount_total: 2198,
            price: {
              id: 'price_1IDQm5JDPojXS6LNM31hxKzp',
              object: 'price',
              active: true,
              billing_scheme: 'per_unit',
              created: 1683237782,
              currency: 'usd',
              custom_unit_amount: null,
              livemode: false,
              lookup_key: null,
              metadata: {},
              nickname: null,
              product: 'prod_NppuJWzzNnD5Ut',
              recurring: null,
              tax_behavior: 'unspecified',
              tiers_mode: null,
              transform_quantity: null,
              type: 'one_time',
              unit_amount: 1099,
              unit_amount_decimal: '1099',
            },
            quantity: 2,
          }
        },
      })),
      list: vitest.fn((id) => ({
        async *[Symbol.asyncIterator]() {
          yield {
            id: id,
            object: 'checkout.session',
            customer: 'cus_123',
            payment_intent: 'pi_123',
            invoice: 'in_123',
            subscription: null,
          }
        },
      })),
    },
  },
  invoices: {
    retrieve: vitest.fn((id) =>
      Promise.resolve({
        id: id,
        object: 'invoice',
        account_country: 'SG',
        account_name: 'Supabase Pte Ltd',
        account_tax_ids: null,
        amount_due: 0,
        amount_paid: 0,
        amount_remaining: 0,
        application_fee_amount: null,
        attempt_count: 0,
        attempted: true,
        auto_advance: false,
        automatic_tax: {
          enabled: false,
          status: null,
        },
        billing_reason: 'subscription_cycle',
        charge: null,
        collection_method: 'charge_automatically',
        created: 1642595534,
        currency: 'usd',
        custom_fields: [
          {
            name: 'Project name',
            value: 'Test Project',
          },
        ],
        customer: 'cus_J7Mkgr8mvbl1eK',
        customer_address: null,
        customer_email: 'tesst@example.com',
        customer_name: null,
        customer_phone: null,
        customer_shipping: null,
        customer_tax_exempt: 'none',
        customer_tax_ids: [],
        default_payment_method: null,
        default_source: null,
        default_tax_rates: [],
        description: null,
        discount: null,
        discounts: [],
        due_date: null,
        ending_balance: 0,
        footer: null,
        hosted_invoice_url:
          'https://invoice.stripe.com/i/acct_1GThseJDPojXS6LN/test_YWNjdF8xR1Roc2VKRFBvalhTNkxOLF9LemNacGRVaG1iQ2NpV0RSTWxUU1lCZmtjcDVvb3pY01008P815B5b',
        invoice_pdf:
          'https://pay.stripe.com/invoice/acct_1GThseJDPojXS6LN/test_YWNjdF8xR1Roc2VKRFBvalhTNkxOLF9LemNacGRVaG1iQ2NpV0RSTWxUU1lCZmtjcDVvb3pY01008P815B5b/pdf',
        last_finalization_error: null,
        lines: {
          object: 'list',
          data: [
            {
              id: 'il_1KJdKkJDPojXS6LN2lyAeJz1',
              object: 'line_item',
              amount: 0,
              currency: 'usd',
              description: '1 × Free tier (at $0.00 / month)',
              discount_amounts: [],
              discountable: true,
              discounts: [],
              livemode: false,
              metadata: {
                project_id: '295',
                project_ref: 'zrsqozfrnjaqcdfbhvgq',
                project_name: 'bar',
                organization_id: '46',
                organization_slug: 'noisy-amethyst-guan',
              },
              period: {
                end: 1645273828,
                start: 1642595428,
              },
              plan: {
                id: 'price_1IDQm5JDPojXS6LNM31hxKzp',
                object: 'plan',
                active: false,
                aggregate_usage: null,
                amount: 0,
                amount_decimal: '0',
                billing_scheme: 'per_unit',
                created: 1611564617,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: false,
                metadata: {},
                nickname: null,
                product: 'prod_Ip4vqwv3EJ7Mi0',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: null,
                usage_type: 'licensed',
              },
              price: {
                id: 'price_1IDQm5JDPojXS6LNM31hxKzp',
                object: 'price',
                active: false,
                billing_scheme: 'per_unit',
                created: 1611564617,
                currency: 'usd',
                livemode: false,
                lookup_key: null,
                metadata: {},
                nickname: null,
                product: 'prod_Ip4vqwv3EJ7Mi0',
                recurring: {
                  aggregate_usage: null,
                  interval: 'month',
                  interval_count: 1,
                  trial_period_days: null,
                  usage_type: 'licensed',
                },
                tax_behavior: 'unspecified',
                tiers_mode: null,
                transform_quantity: null,
                type: 'recurring',
                unit_amount: 0,
                unit_amount_decimal: '0',
              },
              proration: false,
              quantity: 1,
              subscription: 'sub_K4J0aB2bmSyb6b',
              subscription_item: 'si_K4J0IhgijHnskj',
              tax_amounts: [],
              tax_rates: [],
              type: 'subscription',
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/invoices/in_1KJdKkJDPojXS6LNSwSWkZSN/lines',
        },
        livemode: false,
        metadata: {},
        next_payment_attempt: null,
        number: 'B1AB464C-0181',
        on_behalf_of: null,
        paid: true,
        paid_out_of_band: false,
        payment_intent: null,
        payment_settings: {
          payment_method_options: null,
          payment_method_types: null,
        },
        period_end: 1642595428,
        period_start: 1639917028,
        post_payment_credit_notes_amount: 0,
        pre_payment_credit_notes_amount: 0,
        quote: null,
        receipt_number: null,
        starting_balance: 0,
        statement_descriptor: null,
        status: 'paid',
        status_transitions: {
          finalized_at: 1642599192,
          marked_uncollectible_at: null,
          paid_at: 1642599192,
          voided_at: null,
        },
        subscription: 'sub_K4J0aB2bmSyb6b',
        subtotal: 0,
        tax: null,
        tax_percent: null,
        total: 0,
        total_discount_amounts: [],
        total_tax_amounts: [],
        transfer_data: null,
        webhooks_delivered_at: 1642595537,
      })
    ),
    listLineItems: vitest.fn(() => ({
      async *[Symbol.asyncIterator]() {
        yield { id: 'li_123' }
        yield { id: 'li_1234' }
      },
    })),
  },
  subscriptions: {
    retrieve: vitest.fn((id) =>
      Promise.resolve({
        id: id,
        object: 'subscription',
        application_fee_percent: null,
        billing_cycle_anchor: 1623148918,
        billing_thresholds: null,
        cancel_at: null,
        cancel_at_period_end: false,
        canceled_at: null,
        collection_method: 'charge_automatically',
        created: 1623148918,
        current_period_end: 1625740918,
        current_period_start: 1623148918,
        customer: 'cus_IhGfebO16cMIGN',
        days_until_due: null,
        default_payment_method: null,
        default_source: null,
        default_tax_rates: [],
        discount: null,
        ended_at: null,
        items: {
          object: 'list',
          data: [
            {
              id: 'si_JdIzi4Tn5jV9PD',
              object: 'subscription_item',
              billing_thresholds: null,
              created: 1623148918,
              metadata: {},
              plan: {
                id: 'price_1IDQm5JDPojXS6LNM31hxKzp',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 0,
                amount_decimal: '0',
                billing_scheme: 'per_unit',
                created: 1611564617,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: false,
                metadata: {},
                nickname: null,
                product: 'prod_Ip4vqwv3EJ7Mi0',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: null,
                usage_type: 'licensed',
              },
              price: {
                id: 'price_1IDQm5JDPojXS6LNM31hxKzp',
                object: 'price',
                active: true,
                billing_scheme: 'per_unit',
                created: 1611564617,
                currency: 'usd',
                livemode: false,
                lookup_key: null,
                metadata: {},
                nickname: null,
                product: 'prod_Ip4vqwv3EJ7Mi0',
                recurring: {
                  aggregate_usage: null,
                  interval: 'month',
                  interval_count: 1,
                  trial_period_days: null,
                  usage_type: 'licensed',
                },
                tiers_mode: null,
                transform_quantity: null,
                type: 'recurring',
                unit_amount: 0,
                unit_amount_decimal: '0',
              },
              quantity: 1,
              subscription: 'sub_JdIzvfy6o5GZRd',
              tax_rates: [],
            },
            {
              id: 'si_JdIzi4Tn5jVaaa',
              object: 'subscription_item',
              billing_thresholds: null,
              created: 1623148918,
              metadata: {},
              plan: {
                id: 'price_1IDQm5JDPojXS6LNM31hxKzp',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 0,
                amount_decimal: '0',
                billing_scheme: 'per_unit',
                created: 1611564617,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: false,
                metadata: {},
                nickname: null,
                product: 'prod_Ip4vqwv3EJ7Mi0',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: null,
                usage_type: 'licensed',
              },
              price: {
                id: 'price_1IDQm5JDPojXS6LNM31hxKzp',
                object: 'price',
                active: true,
                billing_scheme: 'per_unit',
                created: 1611564617,
                currency: 'usd',
                livemode: false,
                lookup_key: null,
                metadata: {},
                nickname: null,
                product: 'prod_Ip4vqwv3EJ7Mi0',
                recurring: {
                  aggregate_usage: null,
                  interval: 'month',
                  interval_count: 1,
                  trial_period_days: null,
                  usage_type: 'licensed',
                },
                tiers_mode: null,
                transform_quantity: null,
                type: 'recurring',
                unit_amount: 0,
                unit_amount_decimal: '0',
              },
              subscription: 'sub_JdIzvfy6o5GZRd',
              tax_rates: [],
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/subscription_items?subscription=sub_JdIzvfy6o5GZRd',
        },
        latest_invoice: 'in_1J02NeJDPojXS6LNaiyWfNwT',
        livemode: false,
        metadata: {
          project_id: '312',
          project_ref: 'tqevlzwwvzleheqncsph',
          project_name: 'temp webhooks',
          organization_id: '35',
          organization_slug: 'visible-emerald-fly',
        },
        next_pending_invoice_item_invoice: null,
        pause_collection: null,
        pending_invoice_item_interval: null,
        pending_setup_intent: null,
        pending_update: null,
        plan: {
          id: 'price_1IDQm5JDPojXS6LNM31hxKzp',
          object: 'plan',
          active: true,
          aggregate_usage: null,
          amount: 0,
          amount_decimal: '0',
          billing_scheme: 'per_unit',
          created: 1611564617,
          currency: 'usd',
          interval: 'month',
          interval_count: 1,
          livemode: false,
          metadata: {},
          nickname: null,
          product: 'prod_Ip4vqwv3EJ7Mi0',
          tiers: null,
          tiers_mode: null,
          transform_usage: null,
          trial_period_days: null,
          usage_type: 'licensed',
        },
        quantity: 1,
        schedule: null,
        start_date: 1623148918,
        status: 'active',
        tax_percent: null,
        transfer_data: null,
        trial_end: null,
        trial_start: null,
      })
    ),
  },
  customers: {
    retrieve: vitest.fn((id) =>
      Promise.resolve({
        id: id,
        object: 'customer',
        address: null,
        balance: 0,
        created: 1609763141,
        currency: 'usd',
        default_source: null,
        delinquent: false,
        description: '[35 | visible-emerald-fly]: Copple Staging',
        discount: null,
        email: 'billz@supabase.io',
        invoice_prefix: 'D78833AC',
        invoice_settings: {
          custom_fields: null,
          default_payment_method: 'pm_1IfHHPJDPojXS6LNltyTwn3a',
          footer: null,
        },
        livemode: false,
        metadata: {
          supabase_org_id: '35',
        },
        name: 'Copple',
        next_invoice_sequence: 61,
        phone: '+6587498462',
        preferred_locales: [],
        shipping: {
          address: {
            city: '',
            country: '',
            line1: '',
            line2: '',
            postal_code: '',
            state: '',
          },
          name: 'Copple',
          phone: '+6587498462',
        },
        sources: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/customers/cus_IhGfebO16cMIGN/sources',
        },
        subscriptions: {},
        tax_exempt: 'none',
        tax_ids: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/customers/cus_IhGfebO16cMIGN/tax_ids',
        },
      })
    ),
  },
  charges: {
    retrieve: vitest.fn((id) =>
      Promise.resolve({
        id,
        object: 'charge',
        amount: 3000,
        amount_captured: 3000,
        amount_refunded: 0,
        application: null,
        application_fee: null,
        application_fee_amount: null,
        balance_transaction: 'txn_3KtQThJDPojXS6LN0ClROjTy',
        billing_details: {
          address: {
            city: null,
            country: 'AU',
            line1: null,
            line2: null,
            postal_code: null,
            state: null,
          },
          email: null,
          name: null,
          phone: null,
        },
        calculated_statement_descriptor: 'SUPABASE',
        captured: true,
        created: 1651125926,
        currency: 'usd',
        customer: 'cus_J7Mkgr8mvbl1eK',
        description: 'Subscription update',
        destination: null,
        dispute: null,
        disputed: false,
        failure_balance_transaction: null,
        failure_code: null,
        failure_message: null,
        fraud_details: {},
        invoice: 'in_1KJdKkJDPojXS6LNSwSWkZSN',
        livemode: false,
        metadata: {},
        on_behalf_of: null,
        order: null,
        outcome: {
          network_status: 'approved_by_network',
          reason: null,
          risk_level: 'normal',
          risk_score: 55,
          seller_message: 'Payment complete.',
          type: 'authorized',
        },
        paid: true,
        payment_intent: 'pi_3KtQThJDPojXS6LN0H9EfsjV',
        payment_method: 'pm_1KtQTCJDPojXS6LNmYLNUmTc',
        payment_method_details: {
          card: {
            brand: 'visa',
            checks: {
              address_line1_check: null,
              address_postal_code_check: null,
              cvc_check: 'pass',
            },
            country: 'US',
            exp_month: 4,
            exp_year: 2024,
            fingerprint: 'oPS2CZBviZaiMQyc',
            funding: 'credit',
            installments: null,
            last4: '4242',
            mandate: null,
            network: 'visa',
            three_d_secure: null,
            wallet: null,
          },
          type: 'card',
        },
        receipt_email: null,
        receipt_number: null,
        receipt_url:
          'https://pay.stripe.com/receipts/acct_1GThseJDPojXS6LN/ch_3KtQThJDPojXS6LN0YmgbxGj/rcpt_LabhDLLWN1rPswDktT0KujMSqYV8ROm',
        refunded: false,
        refunds: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/charges/ch_3KtQThJDPojXS6LN0YmgbxGj/refunds',
        },
        review: null,
        shipping: null,
        source: null,
        source_transfer: null,
        statement_descriptor: null,
        statement_descriptor_suffix: null,
        status: 'succeeded',
        transfer_data: null,
        transfer_group: null,
      })
    ),
  },
  paymentIntents: {
    retrieve: vitest.fn((id) =>
      Promise.resolve({
        id,
        object: 'payment_intent',
        amount: 1000,
        amount_capturable: 0,
        amount_details: {
          tip: {},
        },
        amount_received: 0,
        application: null,
        application_fee_amount: null,
        automatic_payment_methods: null,
        canceled_at: null,
        cancellation_reason: null,
        capture_method: 'automatic',
        client_secret: 'pi_abc_secret_abc',
        confirmation_method: 'automatic',
        created: 1620984482,
        currency: 'usd',
        customer: null,
        description: 'Created by stripe.com/docs demo',
        invoice: null,
        last_payment_error: null,
        latest_charge: null,
        livemode: false,
        metadata: {},
        next_action: null,
        on_behalf_of: null,
        payment_method: null,
        payment_method_options: {
          card: {
            installments: null,
            mandate_options: null,
            network: null,
            request_three_d_secure: 'automatic',
          },
        },
        payment_method_types: ['card'],
        processing: null,
        receipt_email: null,
        review: null,
        setup_future_usage: null,
        shipping: null,
        statement_descriptor: null,
        statement_descriptor_suffix: null,
        status: 'requires_payment_method',
        transfer_data: null,
        transfer_group: null,
      })
    ),
  },
  products: {
    retrieve: vitest.fn((id) =>
      Promise.resolve({
        id,
        object: 'product',
        active: true,
        attributes: [],
        created: 1623149335,
        description: null,
        images: [],
        marketing_features: [],
        livemode: false,
        metadata: {},
        name: 'fake product',
        package_dimensions: null,
        shippable: null,
        statement_descriptor: null,
        type: 'service',
        unit_label: null,
        updated: 1623149335,
        url: null,
      })
    ),
  },
  prices: {
    retrieve: vitest.fn((id) =>
      Promise.resolve({
        id,
        object: 'price',
        active: true,
        billing_scheme: 'per_unit',
        created: 1757878102,
        currency: 'usd',
        custom_unit_amount: null,
        livemode: false,
        lookup_key: null,
        metadata: {},
        nickname: null,
        product: 'price_1IDQm5JDPojXS6LNM31hxKzp',
        recurring: null,
        tax_behavior: 'inclusive',
        tiers_mode: null,
        transform_quantity: null,
        type: 'one_time',
        unit_amount: 2000,
        unit_amount_decimal: '2000',
      })
    ),
  },
}
