import type { EntitySchema } from './types'

export const checkoutSessionSchema: EntitySchema = {
  properties: [
    'id',
    'object',
    'adaptive_pricing',
    'after_expiration',
    'allow_promotion_codes',
    'amount_subtotal',
    'amount_total',
    'automatic_tax',
    'billing_address_collection',
    'cancel_url',
    'client_reference_id',
    'client_secret',
    'collected_information',
    'consent',
    'consent_collection',
    'created',
    'currency',
    'currency_conversion',
    'custom_fields',
    'custom_text',
    'customer',
    'customer_creation',
    'customer_details',
    'customer_email',
    'discounts',
    'expires_at',
    'invoice',
    'invoice_creation',
    'livemode',
    'locale',
    'metadata',
    'mode',
    'optional_items',
    'payment_intent',
    'payment_link',
    'payment_method_collection',
    'payment_method_configuration_details',
    'payment_method_options',
    'payment_method_types',
    'payment_status',
    'permissions',
    'phone_number_collection',
    'presentment_details',
    'recovered_from',
    'redirect_on_completion',
    'return_url',
    'saved_payment_method_options',
    'setup_intent',
    'shipping_address_collection',
    'shipping_cost',
    'shipping_details',
    'shipping_options',
    'status',
    'submit_type',
    'subscription',
    'success_url',
    'tax_id_collection',
    'total_details',
    'ui_mode',
    'url',
    'wallet_options',
  ],
} as const

export const checkoutSessionDeletedSchema: EntitySchema = {
  properties: ['id', 'object', 'deleted'],
} as const
