/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health check */
    get: operations['health']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/setup': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Set up destination schema
     * @description Creates destination tables and applies migrations. Safe to call multiple times.
     */
    post: operations['setup']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/teardown': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Tear down destination schema
     * @description Drops destination tables. Irreversible.
     */
    post: operations['teardown']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/check': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Check connector connection
     * @description Validates the source/destination config and tests connectivity.
     */
    get: operations['check']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/read': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Read records from source
     * @description Streams NDJSON messages (records, state, catalog). Optional NDJSON body provides catalog/state as input.
     */
    post: operations['read']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/write': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Write records to destination
     * @description Reads NDJSON messages from the request body and writes them to the destination. Pipe /read output as input.
     */
    post: operations['write']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sync': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Run sync pipeline (read → write)
     * @description Without a request body, reads from the source connector and writes to the destination (backfill mode). With an NDJSON request body, uses the provided messages as input instead of reading from the source (push mode — e.g. piped webhook events).
     */
    post: operations['sync']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/connectors': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List available connectors and their config schemas */
    get: operations['listConnectors']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Message:
      | components['schemas']['RecordMessage']
      | components['schemas']['StateMessage']
      | components['schemas']['CatalogMessage']
      | components['schemas']['LogMessage']
      | components['schemas']['ErrorMessage']
      | components['schemas']['StreamStatusMessage']
    RecordMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'record'
      stream: string
      data: {
        [key: string]: unknown
      }
      emitted_at: number
    }
    StateMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'state'
      stream: string
      data: unknown
    }
    CatalogMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'catalog'
      streams: {
        name: string
        primary_key: string[][]
        json_schema?: {
          [key: string]: unknown
        }
        metadata?: {
          [key: string]: unknown
        }
      }[]
    }
    LogMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'log'
      /** @enum {string} */
      level: 'debug' | 'info' | 'warn' | 'error'
      message: string
    }
    ErrorMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'error'
      /** @enum {string} */
      failure_type: 'config_error' | 'system_error' | 'transient_error' | 'auth_error'
      message: string
      stream?: string
      stack_trace?: string
    }
    StreamStatusMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'stream_status'
      stream: string
      /** @enum {string} */
      status: 'started' | 'running' | 'complete' | 'incomplete'
    }
    DestinationOutput:
      | components['schemas']['StateMessage']
      | components['schemas']['ErrorMessage']
      | components['schemas']['LogMessage']
    PipelineConfig: {
      source: {
        name: string
      } & {
        [key: string]: unknown
      }
      destination: {
        name: string
      } & {
        [key: string]: unknown
      }
      streams?: {
        name: string
        /** @enum {string} */
        sync_mode?: 'incremental' | 'full_refresh'
        fields?: string[]
      }[]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Server is healthy */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @constant */
            ok: true
          }
        }
      }
    }
  }
  setup: {
    parameters: {
      query?: never
      header?: {
        /** @description JSON-encoded PipelineConfig: { source: { name, ...config }, destination: { name, ...config }, streams } */
        'x-pipeline'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Setup complete */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid params */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: unknown
          }
        }
      }
    }
  }
  teardown: {
    parameters: {
      query?: never
      header?: {
        /** @description JSON-encoded PipelineConfig: { source: { name, ...config }, destination: { name, ...config }, streams } */
        'x-pipeline'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Teardown complete */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid params */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: unknown
          }
        }
      }
    }
  }
  check: {
    parameters: {
      query?: never
      header?: {
        /** @description JSON-encoded PipelineConfig: { source: { name, ...config }, destination: { name, ...config }, streams } */
        'x-pipeline'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Connection check result */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            source: {
              /** @enum {string} */
              status: 'succeeded' | 'failed'
              message?: string
            }
            destination: {
              /** @enum {string} */
              status: 'succeeded' | 'failed'
              message?: string
            }
          }
        }
      }
      /** @description Invalid params */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: unknown
          }
        }
      }
    }
  }
  read: {
    parameters: {
      query?: never
      header?: {
        /** @description JSON-encoded PipelineConfig: { source: { name, ...config }, destination: { name, ...config }, streams } */
        'x-pipeline'?: string
        /** @description JSON-encoded per-stream cursor state. Engine uses this if present, falls back to StateStore. */
        'x-state'?: string
        /** @description When set, stops streaming after N state checkpoint messages. Enables page-at-a-time sync. */
        'x-state-checkpoint-limit'?: number
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description NDJSON stream of sync messages */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/x-ndjson': components['schemas']['Message']
        }
      }
      /** @description Invalid params */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: unknown
          }
        }
      }
    }
  }
  write: {
    parameters: {
      query?: never
      header?: {
        /** @description JSON-encoded PipelineConfig: { source: { name, ...config }, destination: { name, ...config }, streams } */
        'x-pipeline'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/x-ndjson': components['schemas']['Message']
      }
    }
    responses: {
      /** @description NDJSON stream of write result messages */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/x-ndjson': components['schemas']['DestinationOutput']
        }
      }
      /** @description Invalid params */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: unknown
          }
        }
      }
    }
  }
  sync: {
    parameters: {
      query?: never
      header?: {
        /** @description JSON-encoded PipelineConfig: { source: { name, ...config }, destination: { name, ...config }, streams } */
        'x-pipeline'?: string
        /** @description JSON-encoded per-stream cursor state. Engine uses this if present, falls back to StateStore. */
        'x-state'?: string
        /** @description When set, stops streaming after N state checkpoint messages. Enables page-at-a-time sync. */
        'x-state-checkpoint-limit'?: number
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description NDJSON stream of sync messages */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/x-ndjson': components['schemas']['DestinationOutput']
        }
      }
      /** @description Invalid params */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: unknown
          }
        }
      }
    }
  }
  listConnectors: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Available connectors with their JSON Schema configs */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            sources: {
              [key: string]: {
                config_schema: {
                  [key: string]: unknown
                }
              }
            }
            destinations: {
              [key: string]: {
                config_schema: {
                  [key: string]: unknown
                }
              }
            }
          }
        }
      }
    }
  }
}
