// Generated by scripts/generate-versions.mjs — do not edit manually.
// Union of all deprecated GET paths across all known Stripe API versions.
// Generated by scanning the bundled spec plus every spec published in the CDN.
export const DEPRECATED_PATHS_BUNDLED_VERSION = '2026-03-25.dahlia'

export const GLOBALLY_DEPRECATED_PATHS: ReadonlySet<string> = new Set([
  '/v1/bitcoin/receivers',
  '/v1/bitcoin/receivers/{id}',
  '/v1/bitcoin/receivers/{receiver}/transactions',
  '/v1/bitcoin/transactions',
  '/v1/customers/{customer}/bank_accounts',
  '/v1/customers/{customer}/bank_accounts/{id}',
  '/v1/customers/{customer}/cards',
  '/v1/customers/{customer}/cards/{id}',
  '/v1/exchange_rates',
  '/v1/exchange_rates/{rate_id}',
  '/v1/issuer_fraud_records',
  '/v1/issuer_fraud_records/{issuer_fraud_record}',
  '/v1/recipients',
  '/v1/recipients/{id}',
])
