services:
  temporal-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
    ports: ['5433:5432']
  temporal:
    image: temporalio/auto-setup:latest
    ports: ['7233:7233']
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-db
    depends_on:
      - temporal-db
  temporal-ui:
    image: temporalio/ui:latest
    ports: ['8080:8080']
    environment:
      TEMPORAL_ADDRESS: temporal:7233
    depends_on:
      - temporal
