/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pipelines */
        get: operations["pipelines.list"];
        put?: never;
        /** Create pipeline */
        post: operations["pipelines.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve pipeline */
        get: operations["pipelines.get"];
        put?: never;
        post?: never;
        /** Delete pipeline */
        delete: operations["pipelines.delete"];
        options?: never;
        head?: never;
        /** Update pipeline */
        patch: operations["pipelines.update"];
        trace?: never;
    };
    "/webhooks/{pipeline_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a Stripe webhook event
         * @description Receives a raw Stripe webhook event, verifies its signature using the pipeline's webhook secret, and enqueues it for processing by the active pipeline.
         */
        post: operations["webhooks.push"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SourceConfig: {
            /** @constant */
            type: "stripe";
            stripe: components["schemas"]["SourceStripeConfig"];
        };
        SourceStripeConfig: {
            /** @description Stripe API key (sk_test_... or sk_live_...) */
            api_key: string;
            /** @description Stripe account ID (resolved from API if omitted) */
            account_id?: string;
            /** @description Whether this is a live mode sync */
            livemode?: boolean;
            /** @enum {string} */
            api_version?: "2026-03-25.dahlia" | "2026-02-25.clover" | "2026-01-28.clover" | "2025-12-15.clover" | "2025-11-17.clover" | "2025-10-29.clover" | "2025-09-30.clover" | "2025-08-27.basil" | "2025-07-30.basil" | "2025-06-30.basil" | "2025-05-28.basil" | "2025-04-30.basil" | "2025-03-31.basil" | "2025-02-24.acacia" | "2025-01-27.acacia" | "2024-12-18.acacia" | "2024-11-20.acacia" | "2024-10-28.acacia" | "2024-09-30.acacia" | "2024-06-20" | "2024-04-10" | "2024-04-03" | "2023-10-16" | "2023-08-16" | "2022-11-15" | "2022-08-01" | "2020-08-27" | "2020-03-02" | "2019-12-03" | "2019-11-05" | "2019-10-17" | "2019-10-08" | "2019-09-09" | "2019-08-14" | "2019-05-16" | "2019-03-14" | "2019-02-19" | "2019-02-11" | "2018-11-08" | "2018-10-31" | "2018-09-24" | "2018-09-06" | "2018-08-23" | "2018-07-27" | "2018-05-21" | "2018-02-28" | "2018-02-06" | "2018-02-05" | "2018-01-23" | "2017-12-14" | "2017-08-15";
            /**
             * Format: uri
             * @description Override the Stripe API base URL (e.g. http://localhost:12111 for stripe-mock)
             */
            base_url?: string;
            /**
             * Format: uri
             * @description URL for managed webhook endpoint registration
             */
            webhook_url?: string;
            /** @description Webhook signing secret (whsec_...) for signature verification */
            webhook_secret?: string;
            /** @description Enable WebSocket streaming for live events */
            websocket?: boolean;
            /** @description Enable events API polling for incremental sync after backfill */
            poll_events?: boolean;
            /** @description Port for built-in webhook HTTP listener (e.g. 4242) */
            webhook_port?: number;
            /** @description Object types to re-fetch from Stripe API on webhook (e.g. ["subscription"]) */
            revalidate_objects?: string[];
            /** @description Max objects to backfill per stream (useful for testing) */
            backfill_limit?: number;
            /** @description Max streams paginating in parallel (default: 5, capped at catalog size). */
            max_concurrent_streams?: number;
        };
        DestinationConfig: {
            /** @constant */
            type: "postgres";
            postgres: components["schemas"]["DestinationPostgresConfig"];
        } | {
            /** @constant */
            type: "google_sheets";
            google_sheets: components["schemas"]["DestinationGoogleSheetsConfig"];
        };
        DestinationPostgresConfig: {
            /** @description Postgres connection string (alias for connection_string) */
            url?: string;
            /** @description Postgres connection string */
            connection_string?: string;
            /** @description Postgres host (required for AWS IAM) */
            host?: string;
            /**
             * @description Postgres port
             * @default 5432
             */
            port: number;
            /** @description Database name (required for AWS IAM) */
            database?: string;
            /** @description Database user (required for AWS IAM) */
            user?: string;
            /** @description Target schema name (e.g. "stripe_sync") */
            schema: string;
            /**
             * @description Records to buffer before flushing
             * @default 100
             */
            batch_size: number;
            /** @description AWS RDS IAM authentication config */
            aws?: {
                /** @description AWS region for RDS instance */
                region: string;
                /** @description IAM role ARN to assume (cross-account) */
                role_arn?: string;
                /** @description External ID for STS AssumeRole */
                external_id?: string;
            };
            /** @description PEM-encoded CA certificate for SSL verification (required for verify-ca / verify-full with a private CA) */
            ssl_ca_pem?: string;
        };
        DestinationGoogleSheetsConfig: {
            /** @description Google OAuth2 client ID (env: GOOGLE_CLIENT_ID) */
            client_id?: string;
            /** @description Google OAuth2 client secret (env: GOOGLE_CLIENT_SECRET) */
            client_secret?: string;
            /** @description OAuth2 access token */
            access_token: string;
            /** @description OAuth2 refresh token */
            refresh_token: string;
            /** @description Target spreadsheet ID (created if omitted) */
            spreadsheet_id?: string;
            /**
             * @description Title when creating a new spreadsheet
             * @default Stripe Sync
             */
            spreadsheet_title: string;
            /**
             * @description Rows per Sheets API append call
             * @default 50
             */
            batch_size: number;
        };
        /** @description Full sync checkpoint with separate sections for source, destination, and engine. Connectors only see their own section; the engine manages routing. */
        SyncState: {
            /** @description Source connector state — cursors, backfill progress, events cursors. */
            source: {
                /** @description Per-stream checkpoint data, keyed by stream name. */
                streams: {
                    [key: string]: unknown;
                };
                /** @description Section-wide state shared across all streams. */
                global: {
                    [key: string]: unknown;
                };
            };
            /** @description Destination connector state — reserved for future use. */
            destination: {
                /** @description Per-stream checkpoint data, keyed by stream name. */
                streams: {
                    [key: string]: unknown;
                };
                /** @description Section-wide state shared across all streams. */
                global: {
                    [key: string]: unknown;
                };
            };
            /** @description Engine-managed state — cumulative record counts, sync metadata not owned by connectors. */
            engine: {
                /** @description Per-stream checkpoint data, keyed by stream name. */
                streams: {
                    [key: string]: unknown;
                };
                /** @description Section-wide state shared across all streams. */
                global: {
                    [key: string]: unknown;
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        hostname: string;
                    };
                };
            };
        };
    };
    "pipelines.list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of pipelines */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @description Unique pipeline identifier (e.g. pipe_abc123). */
                            id: string;
                            source: components["schemas"]["SourceConfig"];
                            destination: components["schemas"]["DestinationConfig"];
                            /** @description Selected streams to sync. All streams synced if omitted. */
                            streams?: {
                                /** @description Stream (table) name to sync. */
                                name: string;
                                /**
                                 * @description How the source reads this stream. Defaults to full_refresh.
                                 * @enum {string}
                                 */
                                sync_mode?: "incremental" | "full_refresh";
                                /** @description Cap backfill to this many records, then mark the stream complete. */
                                backfill_limit?: number;
                            }[];
                            /**
                             * @description User-controlled lifecycle state. Set via PATCH to pause, resume, or delete.
                             * @default active
                             * @enum {string}
                             */
                            desired_status: "active" | "paused" | "deleted";
                            /**
                             * @description Workflow-controlled execution state. Updated by the Temporal workflow.
                             * @default setup
                             * @enum {string}
                             */
                            status: "setup" | "backfill" | "ready" | "paused" | "teardown" | "error";
                            /** @description Latest read-only sync progress snapshot from the engine. Updated when a bounded sync run completes and safe for dashboards to poll. */
                            progress?: {
                                /**
                                 * @description Why the sync run ended.
                                 * @enum {string}
                                 */
                                reason: "complete" | "state_limit" | "time_limit" | "error" | "aborted";
                                /**
                                 * @description Present when reason is time_limit. soft = stopped gracefully between messages; hard = forcibly interrupted a blocked operation.
                                 * @enum {string}
                                 */
                                cutoff?: "soft" | "hard";
                                /** @description Wall-clock milliseconds elapsed since the stream started. Always present when reason is time_limit or aborted. */
                                elapsed_ms?: number;
                                /** @description Full sync state at the end of the run. source: accumulated from source_state messages; engine: updated cumulative record counts; destination: reserved. Consumers can persist this directly and pass it back on resume. */
                                state?: components["schemas"]["SyncState"];
                                /** @description Final global aggregates. Same shape as trace/progress. */
                                global_progress?: {
                                    /** @description Wall-clock milliseconds since the sync run started. */
                                    elapsed_ms: number;
                                    /** @description Total records synced across all streams in this run. */
                                    run_record_count: number;
                                    /** @description Overall throughput for the entire run: run_record_count / elapsed seconds. */
                                    rows_per_second: number;
                                    /** @description Instantaneous throughput: total records in last window / window duration. Measures only the most recent reporting interval. */
                                    window_rows_per_second: number;
                                    /** @description Total source_state messages observed so far in this sync run. */
                                    state_checkpoint_count: number;
                                };
                                /** @description Per-stream end-of-sync summary. Errors only appear here, not in stream_status messages. */
                                stream_progress?: {
                                    [key: string]: {
                                        /**
                                         * @description Final stream status.
                                         * @enum {string}
                                         */
                                        status: "start" | "running" | "complete" | "range_complete" | "transient_error" | "system_error" | "config_error" | "auth_error";
                                        /** @description Cumulative records synced for this stream across all runs. */
                                        cumulative_record_count: number;
                                        /** @description Records synced in this run. */
                                        run_record_count: number;
                                        /** @description Average records/sec for this stream over the run. */
                                        records_per_second?: number;
                                        /** @description Average requests/sec for this stream over the run. */
                                        requests_per_second?: number;
                                        /** @description All accumulated errors for this stream during this run. */
                                        errors?: {
                                            /** @description Human-readable error description. */
                                            message: string;
                                            /**
                                             * @description Error category matching TraceError.failure_type.
                                             * @enum {string}
                                             */
                                            failure_type?: "config_error" | "system_error" | "transient_error" | "auth_error";
                                        }[];
                                    };
                                };
                            };
                        }[];
                        has_more: boolean;
                    };
                };
            };
        };
    };
    "pipelines.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    source: components["schemas"]["SourceConfig"];
                    destination: components["schemas"]["DestinationConfig"];
                    /** @description Selected streams to sync. All streams synced if omitted. */
                    streams?: {
                        /** @description Stream (table) name to sync. */
                        name: string;
                        /**
                         * @description How the source reads this stream. Defaults to full_refresh.
                         * @enum {string}
                         */
                        sync_mode?: "incremental" | "full_refresh";
                        /** @description Cap backfill to this many records, then mark the stream complete. */
                        backfill_limit?: number;
                    }[];
                };
            };
        };
        responses: {
            /** @description Created pipeline */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Unique pipeline identifier (e.g. pipe_abc123). */
                        id: string;
                        source: components["schemas"]["SourceConfig"];
                        destination: components["schemas"]["DestinationConfig"];
                        /** @description Selected streams to sync. All streams synced if omitted. */
                        streams?: {
                            /** @description Stream (table) name to sync. */
                            name: string;
                            /**
                             * @description How the source reads this stream. Defaults to full_refresh.
                             * @enum {string}
                             */
                            sync_mode?: "incremental" | "full_refresh";
                            /** @description Cap backfill to this many records, then mark the stream complete. */
                            backfill_limit?: number;
                        }[];
                        /**
                         * @description User-controlled lifecycle state. Set via PATCH to pause, resume, or delete.
                         * @default active
                         * @enum {string}
                         */
                        desired_status: "active" | "paused" | "deleted";
                        /**
                         * @description Workflow-controlled execution state. Updated by the Temporal workflow.
                         * @default setup
                         * @enum {string}
                         */
                        status: "setup" | "backfill" | "ready" | "paused" | "teardown" | "error";
                        /** @description Latest read-only sync progress snapshot from the engine. Updated when a bounded sync run completes and safe for dashboards to poll. */
                        progress?: {
                            /**
                             * @description Why the sync run ended.
                             * @enum {string}
                             */
                            reason: "complete" | "state_limit" | "time_limit" | "error" | "aborted";
                            /**
                             * @description Present when reason is time_limit. soft = stopped gracefully between messages; hard = forcibly interrupted a blocked operation.
                             * @enum {string}
                             */
                            cutoff?: "soft" | "hard";
                            /** @description Wall-clock milliseconds elapsed since the stream started. Always present when reason is time_limit or aborted. */
                            elapsed_ms?: number;
                            /** @description Full sync state at the end of the run. source: accumulated from source_state messages; engine: updated cumulative record counts; destination: reserved. Consumers can persist this directly and pass it back on resume. */
                            state?: components["schemas"]["SyncState"];
                            /** @description Final global aggregates. Same shape as trace/progress. */
                            global_progress?: {
                                /** @description Wall-clock milliseconds since the sync run started. */
                                elapsed_ms: number;
                                /** @description Total records synced across all streams in this run. */
                                run_record_count: number;
                                /** @description Overall throughput for the entire run: run_record_count / elapsed seconds. */
                                rows_per_second: number;
                                /** @description Instantaneous throughput: total records in last window / window duration. Measures only the most recent reporting interval. */
                                window_rows_per_second: number;
                                /** @description Total source_state messages observed so far in this sync run. */
                                state_checkpoint_count: number;
                            };
                            /** @description Per-stream end-of-sync summary. Errors only appear here, not in stream_status messages. */
                            stream_progress?: {
                                [key: string]: {
                                    /**
                                     * @description Final stream status.
                                     * @enum {string}
                                     */
                                    status: "start" | "running" | "complete" | "range_complete" | "transient_error" | "system_error" | "config_error" | "auth_error";
                                    /** @description Cumulative records synced for this stream across all runs. */
                                    cumulative_record_count: number;
                                    /** @description Records synced in this run. */
                                    run_record_count: number;
                                    /** @description Average records/sec for this stream over the run. */
                                    records_per_second?: number;
                                    /** @description Average requests/sec for this stream over the run. */
                                    requests_per_second?: number;
                                    /** @description All accumulated errors for this stream during this run. */
                                    errors?: {
                                        /** @description Human-readable error description. */
                                        message: string;
                                        /**
                                         * @description Error category matching TraceError.failure_type.
                                         * @enum {string}
                                         */
                                        failure_type?: "config_error" | "system_error" | "transient_error" | "auth_error";
                                    }[];
                                };
                            };
                        };
                    };
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
        };
    };
    "pipelines.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retrieved pipeline with status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Unique pipeline identifier (e.g. pipe_abc123). */
                        id: string;
                        source: components["schemas"]["SourceConfig"];
                        destination: components["schemas"]["DestinationConfig"];
                        /** @description Selected streams to sync. All streams synced if omitted. */
                        streams?: {
                            /** @description Stream (table) name to sync. */
                            name: string;
                            /**
                             * @description How the source reads this stream. Defaults to full_refresh.
                             * @enum {string}
                             */
                            sync_mode?: "incremental" | "full_refresh";
                            /** @description Cap backfill to this many records, then mark the stream complete. */
                            backfill_limit?: number;
                        }[];
                        /**
                         * @description User-controlled lifecycle state. Set via PATCH to pause, resume, or delete.
                         * @default active
                         * @enum {string}
                         */
                        desired_status: "active" | "paused" | "deleted";
                        /**
                         * @description Workflow-controlled execution state. Updated by the Temporal workflow.
                         * @default setup
                         * @enum {string}
                         */
                        status: "setup" | "backfill" | "ready" | "paused" | "teardown" | "error";
                        /** @description Latest read-only sync progress snapshot from the engine. Updated when a bounded sync run completes and safe for dashboards to poll. */
                        progress?: {
                            /**
                             * @description Why the sync run ended.
                             * @enum {string}
                             */
                            reason: "complete" | "state_limit" | "time_limit" | "error" | "aborted";
                            /**
                             * @description Present when reason is time_limit. soft = stopped gracefully between messages; hard = forcibly interrupted a blocked operation.
                             * @enum {string}
                             */
                            cutoff?: "soft" | "hard";
                            /** @description Wall-clock milliseconds elapsed since the stream started. Always present when reason is time_limit or aborted. */
                            elapsed_ms?: number;
                            /** @description Full sync state at the end of the run. source: accumulated from source_state messages; engine: updated cumulative record counts; destination: reserved. Consumers can persist this directly and pass it back on resume. */
                            state?: components["schemas"]["SyncState"];
                            /** @description Final global aggregates. Same shape as trace/progress. */
                            global_progress?: {
                                /** @description Wall-clock milliseconds since the sync run started. */
                                elapsed_ms: number;
                                /** @description Total records synced across all streams in this run. */
                                run_record_count: number;
                                /** @description Overall throughput for the entire run: run_record_count / elapsed seconds. */
                                rows_per_second: number;
                                /** @description Instantaneous throughput: total records in last window / window duration. Measures only the most recent reporting interval. */
                                window_rows_per_second: number;
                                /** @description Total source_state messages observed so far in this sync run. */
                                state_checkpoint_count: number;
                            };
                            /** @description Per-stream end-of-sync summary. Errors only appear here, not in stream_status messages. */
                            stream_progress?: {
                                [key: string]: {
                                    /**
                                     * @description Final stream status.
                                     * @enum {string}
                                     */
                                    status: "start" | "running" | "complete" | "range_complete" | "transient_error" | "system_error" | "config_error" | "auth_error";
                                    /** @description Cumulative records synced for this stream across all runs. */
                                    cumulative_record_count: number;
                                    /** @description Records synced in this run. */
                                    run_record_count: number;
                                    /** @description Average records/sec for this stream over the run. */
                                    records_per_second?: number;
                                    /** @description Average requests/sec for this stream over the run. */
                                    requests_per_second?: number;
                                    /** @description All accumulated errors for this stream during this run. */
                                    errors?: {
                                        /** @description Human-readable error description. */
                                        message: string;
                                        /**
                                         * @description Error category matching TraceError.failure_type.
                                         * @enum {string}
                                         */
                                        failure_type?: "config_error" | "system_error" | "transient_error" | "auth_error";
                                    }[];
                                };
                            };
                        };
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
        };
    };
    "pipelines.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted pipeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        /** @constant */
                        deleted: true;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
        };
    };
    "pipelines.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    source?: components["schemas"]["SourceConfig"];
                    destination?: components["schemas"]["DestinationConfig"];
                    /** @description Selected streams to sync. All streams synced if omitted. */
                    streams?: {
                        /** @description Stream (table) name to sync. */
                        name: string;
                        /**
                         * @description How the source reads this stream. Defaults to full_refresh.
                         * @enum {string}
                         */
                        sync_mode?: "incremental" | "full_refresh";
                        /** @description Cap backfill to this many records, then mark the stream complete. */
                        backfill_limit?: number;
                    }[];
                    /**
                     * @description Set to "paused" to pause, "active" to resume, "deleted" to tear down.
                     * @enum {string}
                     */
                    desired_status?: "active" | "paused" | "deleted";
                };
            };
        };
        responses: {
            /** @description Updated pipeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Unique pipeline identifier (e.g. pipe_abc123). */
                        id: string;
                        source: components["schemas"]["SourceConfig"];
                        destination: components["schemas"]["DestinationConfig"];
                        /** @description Selected streams to sync. All streams synced if omitted. */
                        streams?: {
                            /** @description Stream (table) name to sync. */
                            name: string;
                            /**
                             * @description How the source reads this stream. Defaults to full_refresh.
                             * @enum {string}
                             */
                            sync_mode?: "incremental" | "full_refresh";
                            /** @description Cap backfill to this many records, then mark the stream complete. */
                            backfill_limit?: number;
                        }[];
                        /**
                         * @description User-controlled lifecycle state. Set via PATCH to pause, resume, or delete.
                         * @default active
                         * @enum {string}
                         */
                        desired_status: "active" | "paused" | "deleted";
                        /**
                         * @description Workflow-controlled execution state. Updated by the Temporal workflow.
                         * @default setup
                         * @enum {string}
                         */
                        status: "setup" | "backfill" | "ready" | "paused" | "teardown" | "error";
                        /** @description Latest read-only sync progress snapshot from the engine. Updated when a bounded sync run completes and safe for dashboards to poll. */
                        progress?: {
                            /**
                             * @description Why the sync run ended.
                             * @enum {string}
                             */
                            reason: "complete" | "state_limit" | "time_limit" | "error" | "aborted";
                            /**
                             * @description Present when reason is time_limit. soft = stopped gracefully between messages; hard = forcibly interrupted a blocked operation.
                             * @enum {string}
                             */
                            cutoff?: "soft" | "hard";
                            /** @description Wall-clock milliseconds elapsed since the stream started. Always present when reason is time_limit or aborted. */
                            elapsed_ms?: number;
                            /** @description Full sync state at the end of the run. source: accumulated from source_state messages; engine: updated cumulative record counts; destination: reserved. Consumers can persist this directly and pass it back on resume. */
                            state?: components["schemas"]["SyncState"];
                            /** @description Final global aggregates. Same shape as trace/progress. */
                            global_progress?: {
                                /** @description Wall-clock milliseconds since the sync run started. */
                                elapsed_ms: number;
                                /** @description Total records synced across all streams in this run. */
                                run_record_count: number;
                                /** @description Overall throughput for the entire run: run_record_count / elapsed seconds. */
                                rows_per_second: number;
                                /** @description Instantaneous throughput: total records in last window / window duration. Measures only the most recent reporting interval. */
                                window_rows_per_second: number;
                                /** @description Total source_state messages observed so far in this sync run. */
                                state_checkpoint_count: number;
                            };
                            /** @description Per-stream end-of-sync summary. Errors only appear here, not in stream_status messages. */
                            stream_progress?: {
                                [key: string]: {
                                    /**
                                     * @description Final stream status.
                                     * @enum {string}
                                     */
                                    status: "start" | "running" | "complete" | "range_complete" | "transient_error" | "system_error" | "config_error" | "auth_error";
                                    /** @description Cumulative records synced for this stream across all runs. */
                                    cumulative_record_count: number;
                                    /** @description Records synced in this run. */
                                    run_record_count: number;
                                    /** @description Average records/sec for this stream over the run. */
                                    records_per_second?: number;
                                    /** @description Average requests/sec for this stream over the run. */
                                    requests_per_second?: number;
                                    /** @description All accumulated errors for this stream during this run. */
                                    errors?: {
                                        /** @description Human-readable error description. */
                                        message: string;
                                        /**
                                         * @description Error category matching TraceError.failure_type.
                                         * @enum {string}
                                         */
                                        failure_type?: "config_error" | "system_error" | "transient_error" | "auth_error";
                                    }[];
                                };
                            };
                        };
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
            /** @description Invalid status transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: unknown;
                    };
                };
            };
        };
    };
    "webhooks.push": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pipeline_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": "ok";
                };
            };
        };
    };
}
