import type { EntitySchema } from './types'

export const paymentIntentSchema: EntitySchema = {
  properties: [
    'id',
    'object',
    'amount',
    'amount_capturable',
    'amount_details',
    'amount_received',
    'application',
    'application_fee_amount',
    'automatic_payment_methods',
    'canceled_at',
    'cancellation_reason',
    'capture_method',
    'client_secret',
    'confirmation_method',
    'created',
    'currency',
    'customer',
    'description',
    'invoice',
    'last_payment_error',
    'livemode',
    'metadata',
    'next_action',
    'on_behalf_of',
    'payment_method',
    'payment_method_options',
    'payment_method_types',
    'processing',
    'receipt_email',
    'review',
    'setup_future_usage',
    'shipping',
    'statement_descriptor',
    'statement_descriptor_suffix',
    'status',
    'transfer_data',
    'transfer_group',
  ],
} as const
