import type { EntitySchema } from './types'

export const subscriptionSchema: EntitySchema = {
  properties: [
    'id',
    'object',
    'cancel_at_period_end',
    'current_period_end',
    'current_period_start',
    'default_payment_method',
    'items',
    'metadata',
    'pending_setup_intent',
    'pending_update',
    'status',
    'application_fee_percent',
    'billing_cycle_anchor',
    'billing_thresholds',
    'cancel_at',
    'canceled_at',
    'collection_method',
    'created',
    'days_until_due',
    'default_source',
    'default_tax_rates',
    'discount',
    'ended_at',
    'livemode',
    'next_pending_invoice_item_invoice',
    'pause_collection',
    'pending_invoice_item_interval',
    'start_date',
    'transfer_data',
    'trial_end',
    'trial_start',
    'schedule',
    'customer',
    'latest_invoice',
    'plan',
  ],
} as const
