source 'https://rubygems.org'

gem 'temporalio', '~> 1.3'
gem 'faraday', '~> 2.0'

group :development do
  gem 'ruby-lsp'
end

group :test do
  gem 'rspec', '~> 3.0'
  gem 'pg', '~> 1.5'
  gem 'stripe', '~> 15.0'
  gem 'webrick', '~> 1.8'
end
