name: Docs

on:
  push:
    branches: [main, v2]
    paths: [docs/**]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Build docs
        run: cd docs && npm install && npm run build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/out

      - id: deployment
        uses: actions/deploy-pages@v4
